spring:
  application:
    name: taskService

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    hikari:
      minimum-idle: 2
      maximum-pool-size: 10