spring:
  application:
    name: taskService

#  jpa:
#    database: postgresql
#    show-sql: true
#    hibernate:
#      ddl-auto: validate
#
#  datasource:
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#
#    hikari:
#      minimum-idle: 2
#      maximum-pool-size: 10
