package org.app.taskservice.dao.entity

import jakarta.persistence.CascadeType
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.FetchType
import jakarta.persistence.GeneratedValue
import jakarta.persistence.Id
import jakarta.persistence.ManyToMany
import jakarta.persistence.Table
import java.util.UUID

@Entity
@Table(name = "labels")
class LabelEntity(
    @Id
    @GeneratedValue(generator = "UUID")
    @Column(name = "id")
    val id: UUID? = null,

    @Column(name = "name")
    var name: String,

    @Column(name = "color")
    @Enumerated(EnumType.STRING)
    var color: LabelColor?,

    @ManyToMany(mappedBy = "labels", fetch = FetchType.EAGER, cascade = [CascadeType.MERGE])
    var tasks: List<TaskEntity>,
) {
    fun setId(value: UUID) {
        throw UnsupportedOperationException("ID is autogenerated and cannot be changed")
    }

    constructor() : this(null, "", null, emptyList())
}


enum class LabelColor {
    RED,
    ORANGE,
    YELLOW,
    GREEN,
    BLUE,
    PURPLE,
    PINK,
    GRAY
}