package org.app.taskservice.dao.entity

import jakarta.persistence.CascadeType
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.FetchType
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.OneToMany
import jakarta.persistence.Table
import java.util.UUID

@Entity
@Table(name = "partitions")
class PartitionEntity(
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id")
    val id: UUID? = null,
    @Column(name = "title")
    var title: String,

    @ManyToOne
    @JoinColumn(name = "project_id")
    var project: ProjectEntity?,

    @OneToMany(mappedBy = "partition", cascade = [CascadeType.ALL], orphanRemoval = true)
    var tasks: List<TaskEntity> = emptyList(),
) {

    constructor() : this(null, "", null, emptyList())

    fun setId(value: UUID) {
        throw UnsupportedOperationException("ID is autogenerated and cannot be changed")
    }
}
