package org.app.taskservice.dao.entity

import jakarta.persistence.CascadeType
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.OneToMany
import jakarta.persistence.Table
import java.util.UUID

@Entity
@Table(name = "projects")
class ProjectEntity(
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id")
    val id: UUID? = null,
    @Column(name = "title")
    var title: String,
    @Column(name = "user_id")
    var userId: UUID? = null,

    @OneToMany(mappedBy = "project", cascade = [CascadeType.ALL], orphanRemoval = true)
    var partitions: MutableList<PartitionEntity>,
) {
    fun setId(value: UUID) {
        throw UnsupportedOperationException("ID is autogenerated and cannot be changed")
    }

    constructor() : this(null, "", null, mutableListOf())

}